name: Build & Release

on:
  release:
    types: [published]  # triggers when you publish a release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          VERSION=${{ github.event.release.tag_name }}
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            pyinstaller --onefile main.py
            mv dist/main.exe dist/rob-$VERSION.exe
          else
            pyinstaller --onefile --name rob-$VERSION main.py
          fi

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload Binaries to Release
        uses: softprops/action-gh-release@v2
        if: github.event.release.draft == false
        with:
          files: |
            dist/rob-${{ github.event.release.tag_name }}.exe
            dist/rob-${{ github.event.release.tag_name }}-linux
            dist/rob-${{ github.event.release.tag_name }}-mac
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
